/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * it holds the address details of insureds
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

	private static final long serialVersionUID = 501871984;

	private Integer addressId;
	private String  address;
	private String  addressLine_1;
	private String  addressLine_2;
	private String  city;
	private String  state;
	private String  zipPostalCode;
	private String  country;

	public Address() {}

	public Address(Address value) {
		this.addressId = value.addressId;
		this.address = value.address;
		this.addressLine_1 = value.addressLine_1;
		this.addressLine_2 = value.addressLine_2;
		this.city = value.city;
		this.state = value.state;
		this.zipPostalCode = value.zipPostalCode;
		this.country = value.country;
	}

	public Address(
		Integer addressId,
		String  address,
		String  addressLine_1,
		String  addressLine_2,
		String  city,
		String  state,
		String  zipPostalCode,
		String  country
	) {
		this.addressId = addressId;
		this.address = address;
		this.addressLine_1 = addressLine_1;
		this.addressLine_2 = addressLine_2;
		this.city = city;
		this.state = state;
		this.zipPostalCode = zipPostalCode;
		this.country = country;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddressLine_1() {
		return this.addressLine_1;
	}

	public void setAddressLine_1(String addressLine_1) {
		this.addressLine_1 = addressLine_1;
	}

	public String getAddressLine_2() {
		return this.addressLine_2;
	}

	public void setAddressLine_2(String addressLine_2) {
		this.addressLine_2 = addressLine_2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipPostalCode() {
		return this.zipPostalCode;
	}

	public void setZipPostalCode(String zipPostalCode) {
		this.zipPostalCode = zipPostalCode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Address (");

		sb.append(addressId);
		sb.append(", ").append(address);
		sb.append(", ").append(addressLine_1);
		sb.append(", ").append(addressLine_2);
		sb.append(", ").append(city);
		sb.append(", ").append(state);
		sb.append(", ").append(zipPostalCode);
		sb.append(", ").append(country);

		sb.append(")");
		return sb.toString();
	}
}
