/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmountDetails implements Serializable {

	private static final long serialVersionUID = -1890550624;

	private Integer amountId;
	private Double  grossPremiumAmount;
	private Double  terrorismPremiumAmount;
	private Double  serviceTax;
	private Double  serviceTaxAmount;
	private Double  netPremiumAmount;
	private Double  comissionRate;
	private Double  comissionRateAmount;
	private Date    collectionDate;
	private Integer personalDetailId;
	private String  policyNumber;

	public AmountDetails() {}

	public AmountDetails(AmountDetails value) {
		this.amountId = value.amountId;
		this.grossPremiumAmount = value.grossPremiumAmount;
		this.terrorismPremiumAmount = value.terrorismPremiumAmount;
		this.serviceTax = value.serviceTax;
		this.serviceTaxAmount = value.serviceTaxAmount;
		this.netPremiumAmount = value.netPremiumAmount;
		this.comissionRate = value.comissionRate;
		this.comissionRateAmount = value.comissionRateAmount;
		this.collectionDate = value.collectionDate;
		this.personalDetailId = value.personalDetailId;
		this.policyNumber = value.policyNumber;
	}

	public AmountDetails(
		Integer amountId,
		Double  grossPremiumAmount,
		Double  terrorismPremiumAmount,
		Double  serviceTax,
		Double  serviceTaxAmount,
		Double  netPremiumAmount,
		Double  comissionRate,
		Double  comissionRateAmount,
		Date    collectionDate,
		Integer personalDetailId,
		String  policyNumber
	) {
		this.amountId = amountId;
		this.grossPremiumAmount = grossPremiumAmount;
		this.terrorismPremiumAmount = terrorismPremiumAmount;
		this.serviceTax = serviceTax;
		this.serviceTaxAmount = serviceTaxAmount;
		this.netPremiumAmount = netPremiumAmount;
		this.comissionRate = comissionRate;
		this.comissionRateAmount = comissionRateAmount;
		this.collectionDate = collectionDate;
		this.personalDetailId = personalDetailId;
		this.policyNumber = policyNumber;
	}

	public Integer getAmountId() {
		return this.amountId;
	}

	public void setAmountId(Integer amountId) {
		this.amountId = amountId;
	}

	public Double getGrossPremiumAmount() {
		return this.grossPremiumAmount;
	}

	public void setGrossPremiumAmount(Double grossPremiumAmount) {
		this.grossPremiumAmount = grossPremiumAmount;
	}

	public Double getTerrorismPremiumAmount() {
		return this.terrorismPremiumAmount;
	}

	public void setTerrorismPremiumAmount(Double terrorismPremiumAmount) {
		this.terrorismPremiumAmount = terrorismPremiumAmount;
	}

	public Double getServiceTax() {
		return this.serviceTax;
	}

	public void setServiceTax(Double serviceTax) {
		this.serviceTax = serviceTax;
	}

	public Double getServiceTaxAmount() {
		return this.serviceTaxAmount;
	}

	public void setServiceTaxAmount(Double serviceTaxAmount) {
		this.serviceTaxAmount = serviceTaxAmount;
	}

	public Double getNetPremiumAmount() {
		return this.netPremiumAmount;
	}

	public void setNetPremiumAmount(Double netPremiumAmount) {
		this.netPremiumAmount = netPremiumAmount;
	}

	public Double getComissionRate() {
		return this.comissionRate;
	}

	public void setComissionRate(Double comissionRate) {
		this.comissionRate = comissionRate;
	}

	public Double getComissionRateAmount() {
		return this.comissionRateAmount;
	}

	public void setComissionRateAmount(Double comissionRateAmount) {
		this.comissionRateAmount = comissionRateAmount;
	}

	public Date getCollectionDate() {
		return this.collectionDate;
	}

	public void setCollectionDate(Date collectionDate) {
		this.collectionDate = collectionDate;
	}

	public Integer getPersonalDetailId() {
		return this.personalDetailId;
	}

	public void setPersonalDetailId(Integer personalDetailId) {
		this.personalDetailId = personalDetailId;
	}

	public String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("AmountDetails (");

		sb.append(amountId);
		sb.append(", ").append(grossPremiumAmount);
		sb.append(", ").append(terrorismPremiumAmount);
		sb.append(", ").append(serviceTax);
		sb.append(", ").append(serviceTaxAmount);
		sb.append(", ").append(netPremiumAmount);
		sb.append(", ").append(comissionRate);
		sb.append(", ").append(comissionRateAmount);
		sb.append(", ").append(collectionDate);
		sb.append(", ").append(personalDetailId);
		sb.append(", ").append(policyNumber);

		sb.append(")");
		return sb.toString();
	}
}
