/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * it holds doc types
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentsType implements Serializable {

	private static final long serialVersionUID = -1983565339;

	private Integer docTypeId;
	private String  docTypeName;

	public DocumentsType() {}

	public DocumentsType(DocumentsType value) {
		this.docTypeId = value.docTypeId;
		this.docTypeName = value.docTypeName;
	}

	public DocumentsType(
		Integer docTypeId,
		String  docTypeName
	) {
		this.docTypeId = docTypeId;
		this.docTypeName = docTypeName;
	}

	public Integer getDocTypeId() {
		return this.docTypeId;
	}

	public void setDocTypeId(Integer docTypeId) {
		this.docTypeId = docTypeId;
	}

	public String getDocTypeName() {
		return this.docTypeName;
	}

	public void setDocTypeName(String docTypeName) {
		this.docTypeName = docTypeName;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("DocumentsType (");

		sb.append(docTypeId);
		sb.append(", ").append(docTypeName);

		sb.append(")");
		return sb.toString();
	}
}
