/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Onlineusers implements Serializable {

	private static final long serialVersionUID = 958025752;

	private Integer   id;
	private String    primaryEmail;
	private Timestamp logintime;

	public Onlineusers() {}

	public Onlineusers(Onlineusers value) {
		this.id = value.id;
		this.primaryEmail = value.primaryEmail;
		this.logintime = value.logintime;
	}

	public Onlineusers(
		Integer   id,
		String    primaryEmail,
		Timestamp logintime
	) {
		this.id = id;
		this.primaryEmail = primaryEmail;
		this.logintime = logintime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPrimaryEmail() {
		return this.primaryEmail;
	}

	public void setPrimaryEmail(String primaryEmail) {
		this.primaryEmail = primaryEmail;
	}

	public Timestamp getLogintime() {
		return this.logintime;
	}

	public void setLogintime(Timestamp logintime) {
		this.logintime = logintime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Onlineusers (");

		sb.append(id);
		sb.append(", ").append(primaryEmail);
		sb.append(", ").append(logintime);

		sb.append(")");
		return sb.toString();
	}
}
