/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * its holds personal details of insured
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalDetails implements Serializable {

	private static final long serialVersionUID = 1460774906;

	private Integer personalId;
	private String  industry;
	private String  nameOfIndividual;
	private String  nameOfCompany;
	private String  phoneNumber;
	private String  secondaryNumber;
	private String  emailAddress;
	private String  secondrayEmailAddress;
	private Date    dateOfBirth;
	private String  gender;
	private Integer addressId;

	public PersonalDetails() {}

	public PersonalDetails(PersonalDetails value) {
		this.personalId = value.personalId;
		this.industry = value.industry;
		this.nameOfIndividual = value.nameOfIndividual;
		this.nameOfCompany = value.nameOfCompany;
		this.phoneNumber = value.phoneNumber;
		this.secondaryNumber = value.secondaryNumber;
		this.emailAddress = value.emailAddress;
		this.secondrayEmailAddress = value.secondrayEmailAddress;
		this.dateOfBirth = value.dateOfBirth;
		this.gender = value.gender;
		this.addressId = value.addressId;
	}

	public PersonalDetails(
		Integer personalId,
		String  industry,
		String  nameOfIndividual,
		String  nameOfCompany,
		String  phoneNumber,
		String  secondaryNumber,
		String  emailAddress,
		String  secondrayEmailAddress,
		Date    dateOfBirth,
		String  gender,
		Integer addressId
	) {
		this.personalId = personalId;
		this.industry = industry;
		this.nameOfIndividual = nameOfIndividual;
		this.nameOfCompany = nameOfCompany;
		this.phoneNumber = phoneNumber;
		this.secondaryNumber = secondaryNumber;
		this.emailAddress = emailAddress;
		this.secondrayEmailAddress = secondrayEmailAddress;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.addressId = addressId;
	}

	public Integer getPersonalId() {
		return this.personalId;
	}

	public void setPersonalId(Integer personalId) {
		this.personalId = personalId;
	}

	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getNameOfIndividual() {
		return this.nameOfIndividual;
	}

	public void setNameOfIndividual(String nameOfIndividual) {
		this.nameOfIndividual = nameOfIndividual;
	}

	public String getNameOfCompany() {
		return this.nameOfCompany;
	}

	public void setNameOfCompany(String nameOfCompany) {
		this.nameOfCompany = nameOfCompany;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getSecondaryNumber() {
		return this.secondaryNumber;
	}

	public void setSecondaryNumber(String secondaryNumber) {
		this.secondaryNumber = secondaryNumber;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getSecondrayEmailAddress() {
		return this.secondrayEmailAddress;
	}

	public void setSecondrayEmailAddress(String secondrayEmailAddress) {
		this.secondrayEmailAddress = secondrayEmailAddress;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("PersonalDetails (");

		sb.append(personalId);
		sb.append(", ").append(industry);
		sb.append(", ").append(nameOfIndividual);
		sb.append(", ").append(nameOfCompany);
		sb.append(", ").append(phoneNumber);
		sb.append(", ").append(secondaryNumber);
		sb.append(", ").append(emailAddress);
		sb.append(", ").append(secondrayEmailAddress);
		sb.append(", ").append(dateOfBirth);
		sb.append(", ").append(gender);
		sb.append(", ").append(addressId);

		sb.append(")");
		return sb.toString();
	}
}
