/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * its policy details of insured
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicyDetails implements Serializable {

	private static final long serialVersionUID = 1949299676;

	private Integer policyId;
	private String  insuranceType;
	private String  productName;
	private String  policyDetails;
	private Integer personDetailsId;
	private Integer policyTypeId;
	private String  pNumber;

	public PolicyDetails() {}

	public PolicyDetails(PolicyDetails value) {
		this.policyId = value.policyId;
		this.insuranceType = value.insuranceType;
		this.productName = value.productName;
		this.policyDetails = value.policyDetails;
		this.personDetailsId = value.personDetailsId;
		this.policyTypeId = value.policyTypeId;
		this.pNumber = value.pNumber;
	}

	public PolicyDetails(
		Integer policyId,
		String  insuranceType,
		String  productName,
		String  policyDetails,
		Integer personDetailsId,
		Integer policyTypeId,
		String  pNumber
	) {
		this.policyId = policyId;
		this.insuranceType = insuranceType;
		this.productName = productName;
		this.policyDetails = policyDetails;
		this.personDetailsId = personDetailsId;
		this.policyTypeId = policyTypeId;
		this.pNumber = pNumber;
	}

	public Integer getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public String getInsuranceType() {
		return this.insuranceType;
	}

	public void setInsuranceType(String insuranceType) {
		this.insuranceType = insuranceType;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getPolicyDetails() {
		return this.policyDetails;
	}

	public void setPolicyDetails(String policyDetails) {
		this.policyDetails = policyDetails;
	}

	public Integer getPersonDetailsId() {
		return this.personDetailsId;
	}

	public void setPersonDetailsId(Integer personDetailsId) {
		this.personDetailsId = personDetailsId;
	}

	public Integer getPolicyTypeId() {
		return this.policyTypeId;
	}

	public void setPolicyTypeId(Integer policyTypeId) {
		this.policyTypeId = policyTypeId;
	}

	public String getPNumber() {
		return this.pNumber;
	}

	public void setPNumber(String pNumber) {
		this.pNumber = pNumber;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("PolicyDetails (");

		sb.append(policyId);
		sb.append(", ").append(insuranceType);
		sb.append(", ").append(productName);
		sb.append(", ").append(policyDetails);
		sb.append(", ").append(personDetailsId);
		sb.append(", ").append(policyTypeId);
		sb.append(", ").append(pNumber);

		sb.append(")");
		return sb.toString();
	}
}
