/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * it holds the documents of insureds related to policy
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicyDocuments implements Serializable {

	private static final long serialVersionUID = -1097177530;

	private Integer   documentId;
	private String    documentName;
	private Integer   docTypeId;
	private String    comments;
	private Timestamp uploadedDate;
	private String    status;
	private Integer   personDetId;
	private String    policyNumber;
	private byte[]    document;

	public PolicyDocuments() {}

	public PolicyDocuments(PolicyDocuments value) {
		this.documentId = value.documentId;
		this.documentName = value.documentName;
		this.docTypeId = value.docTypeId;
		this.comments = value.comments;
		this.uploadedDate = value.uploadedDate;
		this.status = value.status;
		this.personDetId = value.personDetId;
		this.policyNumber = value.policyNumber;
		this.document = value.document;
	}

	public PolicyDocuments(
		Integer   documentId,
		String    documentName,
		Integer   docTypeId,
		String    comments,
		Timestamp uploadedDate,
		String    status,
		Integer   personDetId,
		String    policyNumber,
		byte[]    document
	) {
		this.documentId = documentId;
		this.documentName = documentName;
		this.docTypeId = docTypeId;
		this.comments = comments;
		this.uploadedDate = uploadedDate;
		this.status = status;
		this.personDetId = personDetId;
		this.policyNumber = policyNumber;
		this.document = document;
	}

	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	public Integer getDocTypeId() {
		return this.docTypeId;
	}

	public void setDocTypeId(Integer docTypeId) {
		this.docTypeId = docTypeId;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Timestamp getUploadedDate() {
		return this.uploadedDate;
	}

	public void setUploadedDate(Timestamp uploadedDate) {
		this.uploadedDate = uploadedDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getPersonDetId() {
		return this.personDetId;
	}

	public void setPersonDetId(Integer personDetId) {
		this.personDetId = personDetId;
	}

	public String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public byte[] getDocument() {
		return this.document;
	}

	public void setDocument(byte[] document) {
		this.document = document;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("PolicyDocuments (");

		sb.append(documentId);
		sb.append(", ").append(documentName);
		sb.append(", ").append(docTypeId);
		sb.append(", ").append(comments);
		sb.append(", ").append(uploadedDate);
		sb.append(", ").append(status);
		sb.append(", ").append(personDetId);
		sb.append(", ").append(policyNumber);
		sb.append(", ").append("[binary...]");

		sb.append(")");
		return sb.toString();
	}
}
