/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

	private static final long serialVersionUID = 1437089380;

	private Integer   id;
	private String    firstName;
	private String    middleName;
	private String    lastName;
	private String    password;
	private String    role;
	private String    primaryEmail;
	private String    primaryPhone;
	private String    status;
	private Timestamp createdOn;
	private Timestamp updatedOn;
	private String    comments;
	private Integer   companyId;

	public User() {}

	public User(User value) {
		this.id = value.id;
		this.firstName = value.firstName;
		this.middleName = value.middleName;
		this.lastName = value.lastName;
		this.password = value.password;
		this.role = value.role;
		this.primaryEmail = value.primaryEmail;
		this.primaryPhone = value.primaryPhone;
		this.status = value.status;
		this.createdOn = value.createdOn;
		this.updatedOn = value.updatedOn;
		this.comments = value.comments;
		this.companyId = value.companyId;
	}

	public User(
		Integer   id,
		String    firstName,
		String    middleName,
		String    lastName,
		String    password,
		String    role,
		String    primaryEmail,
		String    primaryPhone,
		String    status,
		Timestamp createdOn,
		Timestamp updatedOn,
		String    comments,
		Integer   companyId
	) {
		this.id = id;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.password = password;
		this.role = role;
		this.primaryEmail = primaryEmail;
		this.primaryPhone = primaryPhone;
		this.status = status;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.comments = comments;
		this.companyId = companyId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getPrimaryEmail() {
		return this.primaryEmail;
	}

	public void setPrimaryEmail(String primaryEmail) {
		this.primaryEmail = primaryEmail;
	}

	public String getPrimaryPhone() {
		return this.primaryPhone;
	}

	public void setPrimaryPhone(String primaryPhone) {
		this.primaryPhone = primaryPhone;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Timestamp getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Timestamp createdOn) {
		this.createdOn = createdOn;
	}

	public Timestamp getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Timestamp updatedOn) {
		this.updatedOn = updatedOn;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("User (");

		sb.append(id);
		sb.append(", ").append(firstName);
		sb.append(", ").append(middleName);
		sb.append(", ").append(lastName);
		sb.append(", ").append(password);
		sb.append(", ").append(role);
		sb.append(", ").append(primaryEmail);
		sb.append(", ").append(primaryPhone);
		sb.append(", ").append(status);
		sb.append(", ").append(createdOn);
		sb.append(", ").append(updatedOn);
		sb.append(", ").append(comments);
		sb.append(", ").append(companyId);

		sb.append(")");
		return sb.toString();
	}
}
