/**
 * This class is generated by jOOQ
 */
package com.telosws.orm;


import com.telosws.orm.tables.Address;
import com.telosws.orm.tables.AmountDetails;
import com.telosws.orm.tables.DocumentsType;
import com.telosws.orm.tables.InsuranceComapnyDetails;
import com.telosws.orm.tables.Onlineusers;
import com.telosws.orm.tables.PersonalDetails;
import com.telosws.orm.tables.PolicyDetails;
import com.telosws.orm.tables.PolicyDocuments;
import com.telosws.orm.tables.PolicyType;
import com.telosws.orm.tables.SchemaVersion;
import com.telosws.orm.tables.User;
import com.telosws.orm.tables.records.AddressRecord;
import com.telosws.orm.tables.records.AmountDetailsRecord;
import com.telosws.orm.tables.records.DocumentsTypeRecord;
import com.telosws.orm.tables.records.InsuranceComapnyDetailsRecord;
import com.telosws.orm.tables.records.OnlineusersRecord;
import com.telosws.orm.tables.records.PersonalDetailsRecord;
import com.telosws.orm.tables.records.PolicyDetailsRecord;
import com.telosws.orm.tables.records.PolicyDocumentsRecord;
import com.telosws.orm.tables.records.PolicyTypeRecord;
import com.telosws.orm.tables.records.SchemaVersionRecord;
import com.telosws.orm.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>slbroking</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<AddressRecord, Integer> IDENTITY_ADDRESS = Identities0.IDENTITY_ADDRESS;
	public static final Identity<AmountDetailsRecord, Integer> IDENTITY_AMOUNT_DETAILS = Identities0.IDENTITY_AMOUNT_DETAILS;
	public static final Identity<DocumentsTypeRecord, Integer> IDENTITY_DOCUMENTS_TYPE = Identities0.IDENTITY_DOCUMENTS_TYPE;
	public static final Identity<InsuranceComapnyDetailsRecord, Integer> IDENTITY_INSURANCE_COMAPNY_DETAILS = Identities0.IDENTITY_INSURANCE_COMAPNY_DETAILS;
	public static final Identity<OnlineusersRecord, Integer> IDENTITY_ONLINEUSERS = Identities0.IDENTITY_ONLINEUSERS;
	public static final Identity<PersonalDetailsRecord, Integer> IDENTITY_PERSONAL_DETAILS = Identities0.IDENTITY_PERSONAL_DETAILS;
	public static final Identity<PolicyDetailsRecord, Integer> IDENTITY_POLICY_DETAILS = Identities0.IDENTITY_POLICY_DETAILS;
	public static final Identity<PolicyDocumentsRecord, Integer> IDENTITY_POLICY_DOCUMENTS = Identities0.IDENTITY_POLICY_DOCUMENTS;
	public static final Identity<PolicyTypeRecord, Integer> IDENTITY_POLICY_TYPE = Identities0.IDENTITY_POLICY_TYPE;
	public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AddressRecord> KEY_ADDRESS_PRIMARY = UniqueKeys0.KEY_ADDRESS_PRIMARY;
	public static final UniqueKey<AmountDetailsRecord> KEY_AMOUNT_DETAILS_PRIMARY = UniqueKeys0.KEY_AMOUNT_DETAILS_PRIMARY;
	public static final UniqueKey<DocumentsTypeRecord> KEY_DOCUMENTS_TYPE_PRIMARY = UniqueKeys0.KEY_DOCUMENTS_TYPE_PRIMARY;
	public static final UniqueKey<DocumentsTypeRecord> KEY_DOCUMENTS_TYPE_DOC_TYPE_NAME = UniqueKeys0.KEY_DOCUMENTS_TYPE_DOC_TYPE_NAME;
	public static final UniqueKey<InsuranceComapnyDetailsRecord> KEY_INSURANCE_COMAPNY_DETAILS_PRIMARY = UniqueKeys0.KEY_INSURANCE_COMAPNY_DETAILS_PRIMARY;
	public static final UniqueKey<InsuranceComapnyDetailsRecord> KEY_INSURANCE_COMAPNY_DETAILS_POLICY_NUMBER = UniqueKeys0.KEY_INSURANCE_COMAPNY_DETAILS_POLICY_NUMBER;
	public static final UniqueKey<InsuranceComapnyDetailsRecord> KEY_INSURANCE_COMAPNY_DETAILS_ENDORSE_NUMBER = UniqueKeys0.KEY_INSURANCE_COMAPNY_DETAILS_ENDORSE_NUMBER;
	public static final UniqueKey<OnlineusersRecord> KEY_ONLINEUSERS_PRIMARY = UniqueKeys0.KEY_ONLINEUSERS_PRIMARY;
	public static final UniqueKey<OnlineusersRecord> KEY_ONLINEUSERS_PRIMARY_EMAIL_UNIQUE = UniqueKeys0.KEY_ONLINEUSERS_PRIMARY_EMAIL_UNIQUE;
	public static final UniqueKey<PersonalDetailsRecord> KEY_PERSONAL_DETAILS_PRIMARY = UniqueKeys0.KEY_PERSONAL_DETAILS_PRIMARY;
	public static final UniqueKey<PersonalDetailsRecord> KEY_PERSONAL_DETAILS_PHONE_NUMBER = UniqueKeys0.KEY_PERSONAL_DETAILS_PHONE_NUMBER;
	public static final UniqueKey<PersonalDetailsRecord> KEY_PERSONAL_DETAILS_EMAIL_ADDRESS = UniqueKeys0.KEY_PERSONAL_DETAILS_EMAIL_ADDRESS;
	public static final UniqueKey<PolicyDetailsRecord> KEY_POLICY_DETAILS_PRIMARY = UniqueKeys0.KEY_POLICY_DETAILS_PRIMARY;
	public static final UniqueKey<PolicyDocumentsRecord> KEY_POLICY_DOCUMENTS_PRIMARY = UniqueKeys0.KEY_POLICY_DOCUMENTS_PRIMARY;
	public static final UniqueKey<PolicyTypeRecord> KEY_POLICY_TYPE_PRIMARY = UniqueKeys0.KEY_POLICY_TYPE_PRIMARY;
	public static final UniqueKey<PolicyTypeRecord> KEY_POLICY_TYPE_POLICY_TYPE_NAME = UniqueKeys0.KEY_POLICY_TYPE_POLICY_TYPE_NAME;
	public static final UniqueKey<SchemaVersionRecord> KEY_SCHEMA_VERSION_PRIMARY = UniqueKeys0.KEY_SCHEMA_VERSION_PRIMARY;
	public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
	public static final UniqueKey<UserRecord> KEY_USER_PRIMARY_EMAIL_UNIQUE = UniqueKeys0.KEY_USER_PRIMARY_EMAIL_UNIQUE;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<AmountDetailsRecord, PersonalDetailsRecord> PER_DETAILS_ID = ForeignKeys0.PER_DETAILS_ID;
	public static final ForeignKey<AmountDetailsRecord, InsuranceComapnyDetailsRecord> POLICY_NUM_FK = ForeignKeys0.POLICY_NUM_FK;
	public static final ForeignKey<InsuranceComapnyDetailsRecord, PersonalDetailsRecord> PERSONAL_DETAILS_ID = ForeignKeys0.PERSONAL_DETAILS_ID;
	public static final ForeignKey<PersonalDetailsRecord, AddressRecord> ADDRESS_ID = ForeignKeys0.ADDRESS_ID;
	public static final ForeignKey<PolicyDetailsRecord, PersonalDetailsRecord> PERSAONLID = ForeignKeys0.PERSAONLID;
	public static final ForeignKey<PolicyDetailsRecord, PolicyTypeRecord> POLICY_TYPE_ID_FK = ForeignKeys0.POLICY_TYPE_ID_FK;
	public static final ForeignKey<PolicyDetailsRecord, InsuranceComapnyDetailsRecord> P_NUMBER_FKEY = ForeignKeys0.P_NUMBER_FKEY;
	public static final ForeignKey<PolicyDocumentsRecord, DocumentsTypeRecord> DOC_TYPE_FK = ForeignKeys0.DOC_TYPE_FK;
	public static final ForeignKey<PolicyDocumentsRecord, PersonalDetailsRecord> PERSONAL_DETAILS_FK = ForeignKeys0.PERSONAL_DETAILS_FK;
	public static final ForeignKey<PolicyDocumentsRecord, InsuranceComapnyDetailsRecord> POL_NUM_FK = ForeignKeys0.POL_NUM_FK;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<AddressRecord, Integer> IDENTITY_ADDRESS = createIdentity(Address.ADDRESS, Address.ADDRESS.ADDRESS_ID);
		public static Identity<AmountDetailsRecord, Integer> IDENTITY_AMOUNT_DETAILS = createIdentity(AmountDetails.AMOUNT_DETAILS, AmountDetails.AMOUNT_DETAILS.AMOUNT_ID);
		public static Identity<DocumentsTypeRecord, Integer> IDENTITY_DOCUMENTS_TYPE = createIdentity(DocumentsType.DOCUMENTS_TYPE, DocumentsType.DOCUMENTS_TYPE.DOC_TYPE_ID);
		public static Identity<InsuranceComapnyDetailsRecord, Integer> IDENTITY_INSURANCE_COMAPNY_DETAILS = createIdentity(InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS, InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS.INSURANCE_COMPANY_ID);
		public static Identity<OnlineusersRecord, Integer> IDENTITY_ONLINEUSERS = createIdentity(Onlineusers.ONLINEUSERS, Onlineusers.ONLINEUSERS.ID);
		public static Identity<PersonalDetailsRecord, Integer> IDENTITY_PERSONAL_DETAILS = createIdentity(PersonalDetails.PERSONAL_DETAILS, PersonalDetails.PERSONAL_DETAILS.PERSONAL_ID);
		public static Identity<PolicyDetailsRecord, Integer> IDENTITY_POLICY_DETAILS = createIdentity(PolicyDetails.POLICY_DETAILS, PolicyDetails.POLICY_DETAILS.POLICY_ID);
		public static Identity<PolicyDocumentsRecord, Integer> IDENTITY_POLICY_DOCUMENTS = createIdentity(PolicyDocuments.POLICY_DOCUMENTS, PolicyDocuments.POLICY_DOCUMENTS.DOCUMENT_ID);
		public static Identity<PolicyTypeRecord, Integer> IDENTITY_POLICY_TYPE = createIdentity(PolicyType.POLICY_TYPE, PolicyType.POLICY_TYPE.POLICY_TYPE_ID);
		public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AddressRecord> KEY_ADDRESS_PRIMARY = createUniqueKey(Address.ADDRESS, Address.ADDRESS.ADDRESS_ID);
		public static final UniqueKey<AmountDetailsRecord> KEY_AMOUNT_DETAILS_PRIMARY = createUniqueKey(AmountDetails.AMOUNT_DETAILS, AmountDetails.AMOUNT_DETAILS.AMOUNT_ID);
		public static final UniqueKey<DocumentsTypeRecord> KEY_DOCUMENTS_TYPE_PRIMARY = createUniqueKey(DocumentsType.DOCUMENTS_TYPE, DocumentsType.DOCUMENTS_TYPE.DOC_TYPE_ID);
		public static final UniqueKey<DocumentsTypeRecord> KEY_DOCUMENTS_TYPE_DOC_TYPE_NAME = createUniqueKey(DocumentsType.DOCUMENTS_TYPE, DocumentsType.DOCUMENTS_TYPE.DOC_TYPE_NAME);
		public static final UniqueKey<InsuranceComapnyDetailsRecord> KEY_INSURANCE_COMAPNY_DETAILS_PRIMARY = createUniqueKey(InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS, InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS.INSURANCE_COMPANY_ID);
		public static final UniqueKey<InsuranceComapnyDetailsRecord> KEY_INSURANCE_COMAPNY_DETAILS_POLICY_NUMBER = createUniqueKey(InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS, InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS.POLICY_NUMBER);
		public static final UniqueKey<InsuranceComapnyDetailsRecord> KEY_INSURANCE_COMAPNY_DETAILS_ENDORSE_NUMBER = createUniqueKey(InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS, InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS.ENDORSE_NUMBER);
		public static final UniqueKey<OnlineusersRecord> KEY_ONLINEUSERS_PRIMARY = createUniqueKey(Onlineusers.ONLINEUSERS, Onlineusers.ONLINEUSERS.ID);
		public static final UniqueKey<OnlineusersRecord> KEY_ONLINEUSERS_PRIMARY_EMAIL_UNIQUE = createUniqueKey(Onlineusers.ONLINEUSERS, Onlineusers.ONLINEUSERS.PRIMARY_EMAIL);
		public static final UniqueKey<PersonalDetailsRecord> KEY_PERSONAL_DETAILS_PRIMARY = createUniqueKey(PersonalDetails.PERSONAL_DETAILS, PersonalDetails.PERSONAL_DETAILS.PERSONAL_ID);
		public static final UniqueKey<PersonalDetailsRecord> KEY_PERSONAL_DETAILS_PHONE_NUMBER = createUniqueKey(PersonalDetails.PERSONAL_DETAILS, PersonalDetails.PERSONAL_DETAILS.PHONE_NUMBER);
		public static final UniqueKey<PersonalDetailsRecord> KEY_PERSONAL_DETAILS_EMAIL_ADDRESS = createUniqueKey(PersonalDetails.PERSONAL_DETAILS, PersonalDetails.PERSONAL_DETAILS.EMAIL_ADDRESS);
		public static final UniqueKey<PolicyDetailsRecord> KEY_POLICY_DETAILS_PRIMARY = createUniqueKey(PolicyDetails.POLICY_DETAILS, PolicyDetails.POLICY_DETAILS.POLICY_ID);
		public static final UniqueKey<PolicyDocumentsRecord> KEY_POLICY_DOCUMENTS_PRIMARY = createUniqueKey(PolicyDocuments.POLICY_DOCUMENTS, PolicyDocuments.POLICY_DOCUMENTS.DOCUMENT_ID);
		public static final UniqueKey<PolicyTypeRecord> KEY_POLICY_TYPE_PRIMARY = createUniqueKey(PolicyType.POLICY_TYPE, PolicyType.POLICY_TYPE.POLICY_TYPE_ID);
		public static final UniqueKey<PolicyTypeRecord> KEY_POLICY_TYPE_POLICY_TYPE_NAME = createUniqueKey(PolicyType.POLICY_TYPE, PolicyType.POLICY_TYPE.POLICY_TYPE_NAME);
		public static final UniqueKey<SchemaVersionRecord> KEY_SCHEMA_VERSION_PRIMARY = createUniqueKey(SchemaVersion.SCHEMA_VERSION, SchemaVersion.SCHEMA_VERSION.VERSION);
		public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, User.USER.ID);
		public static final UniqueKey<UserRecord> KEY_USER_PRIMARY_EMAIL_UNIQUE = createUniqueKey(User.USER, User.USER.PRIMARY_EMAIL);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<AmountDetailsRecord, PersonalDetailsRecord> PER_DETAILS_ID = createForeignKey(com.telosws.orm.Keys.KEY_PERSONAL_DETAILS_PRIMARY, AmountDetails.AMOUNT_DETAILS, AmountDetails.AMOUNT_DETAILS.PERSONAL_DETAIL_ID);
		public static final ForeignKey<AmountDetailsRecord, InsuranceComapnyDetailsRecord> POLICY_NUM_FK = createForeignKey(com.telosws.orm.Keys.KEY_INSURANCE_COMAPNY_DETAILS_POLICY_NUMBER, AmountDetails.AMOUNT_DETAILS, AmountDetails.AMOUNT_DETAILS.POLICY_NUMBER);
		public static final ForeignKey<InsuranceComapnyDetailsRecord, PersonalDetailsRecord> PERSONAL_DETAILS_ID = createForeignKey(com.telosws.orm.Keys.KEY_PERSONAL_DETAILS_PRIMARY, InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS, InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS.PERSONAL_DETAILS_ID);
		public static final ForeignKey<PersonalDetailsRecord, AddressRecord> ADDRESS_ID = createForeignKey(com.telosws.orm.Keys.KEY_ADDRESS_PRIMARY, PersonalDetails.PERSONAL_DETAILS, PersonalDetails.PERSONAL_DETAILS.ADDRESS_ID);
		public static final ForeignKey<PolicyDetailsRecord, PersonalDetailsRecord> PERSAONLID = createForeignKey(com.telosws.orm.Keys.KEY_PERSONAL_DETAILS_PRIMARY, PolicyDetails.POLICY_DETAILS, PolicyDetails.POLICY_DETAILS.PERSON_DETAILS_ID);
		public static final ForeignKey<PolicyDetailsRecord, PolicyTypeRecord> POLICY_TYPE_ID_FK = createForeignKey(com.telosws.orm.Keys.KEY_POLICY_TYPE_PRIMARY, PolicyDetails.POLICY_DETAILS, PolicyDetails.POLICY_DETAILS.POLICY_TYPE_ID);
		public static final ForeignKey<PolicyDetailsRecord, InsuranceComapnyDetailsRecord> P_NUMBER_FKEY = createForeignKey(com.telosws.orm.Keys.KEY_INSURANCE_COMAPNY_DETAILS_POLICY_NUMBER, PolicyDetails.POLICY_DETAILS, PolicyDetails.POLICY_DETAILS.P_NUMBER);
		public static final ForeignKey<PolicyDocumentsRecord, DocumentsTypeRecord> DOC_TYPE_FK = createForeignKey(com.telosws.orm.Keys.KEY_DOCUMENTS_TYPE_PRIMARY, PolicyDocuments.POLICY_DOCUMENTS, PolicyDocuments.POLICY_DOCUMENTS.DOC_TYPE_ID);
		public static final ForeignKey<PolicyDocumentsRecord, PersonalDetailsRecord> PERSONAL_DETAILS_FK = createForeignKey(com.telosws.orm.Keys.KEY_PERSONAL_DETAILS_PRIMARY, PolicyDocuments.POLICY_DOCUMENTS, PolicyDocuments.POLICY_DOCUMENTS.PERSON_DET_ID);
		public static final ForeignKey<PolicyDocumentsRecord, InsuranceComapnyDetailsRecord> POL_NUM_FK = createForeignKey(com.telosws.orm.Keys.KEY_INSURANCE_COMAPNY_DETAILS_POLICY_NUMBER, PolicyDocuments.POLICY_DOCUMENTS, PolicyDocuments.POLICY_DOCUMENTS.POLICY_NUMBER);
	}
}
