/**
 * This class is generated by jOOQ
 */
package com.telosws.orm;


import com.telosws.orm.tables.Address;
import com.telosws.orm.tables.AmountDetails;
import com.telosws.orm.tables.DocumentsType;
import com.telosws.orm.tables.InsuranceComapnyDetails;
import com.telosws.orm.tables.Onlineusers;
import com.telosws.orm.tables.PersonalDetails;
import com.telosws.orm.tables.PolicyDetails;
import com.telosws.orm.tables.PolicyDocuments;
import com.telosws.orm.tables.PolicyType;
import com.telosws.orm.tables.SchemaVersion;
import com.telosws.orm.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Slbroking extends SchemaImpl {

	private static final long serialVersionUID = -510835671;

	/**
	 * The reference instance of <code>slbroking</code>
	 */
	public static final Slbroking SLBROKING = new Slbroking();

	/**
	 * No further instances allowed
	 */
	private Slbroking() {
		super("slbroking");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Address.ADDRESS,
			AmountDetails.AMOUNT_DETAILS,
			DocumentsType.DOCUMENTS_TYPE,
			InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS,
			Onlineusers.ONLINEUSERS,
			PersonalDetails.PERSONAL_DETAILS,
			PolicyDetails.POLICY_DETAILS,
			PolicyDocuments.POLICY_DOCUMENTS,
			PolicyType.POLICY_TYPE,
			SchemaVersion.SCHEMA_VERSION,
			User.USER);
	}
}
