/**
 * This class is generated by jOOQ
 */
package com.telosws.orm;


import com.telosws.orm.tables.Address;
import com.telosws.orm.tables.AmountDetails;
import com.telosws.orm.tables.DocumentsType;
import com.telosws.orm.tables.InsuranceComapnyDetails;
import com.telosws.orm.tables.Onlineusers;
import com.telosws.orm.tables.PersonalDetails;
import com.telosws.orm.tables.PolicyDetails;
import com.telosws.orm.tables.PolicyDocuments;
import com.telosws.orm.tables.PolicyType;
import com.telosws.orm.tables.SchemaVersion;
import com.telosws.orm.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in slbroking
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * it holds the address details of insureds
	 */
	public static final Address ADDRESS = com.telosws.orm.tables.Address.ADDRESS;

	/**
	 * The table slbroking.amount_details
	 */
	public static final AmountDetails AMOUNT_DETAILS = com.telosws.orm.tables.AmountDetails.AMOUNT_DETAILS;

	/**
	 * it holds doc types
	 */
	public static final DocumentsType DOCUMENTS_TYPE = com.telosws.orm.tables.DocumentsType.DOCUMENTS_TYPE;

	/**
	 * its holds the details of insurance company details of insured policy
	 */
	public static final InsuranceComapnyDetails INSURANCE_COMAPNY_DETAILS = com.telosws.orm.tables.InsuranceComapnyDetails.INSURANCE_COMAPNY_DETAILS;

	/**
	 * The table slbroking.onlineusers
	 */
	public static final Onlineusers ONLINEUSERS = com.telosws.orm.tables.Onlineusers.ONLINEUSERS;

	/**
	 * its holds personal details of insured
	 */
	public static final PersonalDetails PERSONAL_DETAILS = com.telosws.orm.tables.PersonalDetails.PERSONAL_DETAILS;

	/**
	 * its policy details of insured
	 */
	public static final PolicyDetails POLICY_DETAILS = com.telosws.orm.tables.PolicyDetails.POLICY_DETAILS;

	/**
	 * it holds the documents of insureds related to policy
	 */
	public static final PolicyDocuments POLICY_DOCUMENTS = com.telosws.orm.tables.PolicyDocuments.POLICY_DOCUMENTS;

	/**
	 * The table slbroking.policy_type
	 */
	public static final PolicyType POLICY_TYPE = com.telosws.orm.tables.PolicyType.POLICY_TYPE;

	/**
	 * The table slbroking.schema_version
	 */
	public static final SchemaVersion SCHEMA_VERSION = com.telosws.orm.tables.SchemaVersion.SCHEMA_VERSION;

	/**
	 * The table slbroking.user
	 */
	public static final User USER = com.telosws.orm.tables.User.USER;
}
