/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.records;


import com.telosws.orm.tables.AmountDetails;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmountDetailsRecord extends UpdatableRecordImpl<AmountDetailsRecord> implements Record11<Integer, Double, Double, Double, Double, Double, Double, Double, Date, Integer, String> {

	private static final long serialVersionUID = 1034914328;

	/**
	 * Setter for <code>slbroking.amount_details.Amount_ID</code>.
	 */
	public void setAmountId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Amount_ID</code>.
	 */
	public Integer getAmountId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Gross_Premium_Amount</code>.
	 */
	public void setGrossPremiumAmount(Double value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Gross_Premium_Amount</code>.
	 */
	public Double getGrossPremiumAmount() {
		return (Double) getValue(1);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Terrorism_Premium_Amount</code>.
	 */
	public void setTerrorismPremiumAmount(Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Terrorism_Premium_Amount</code>.
	 */
	public Double getTerrorismPremiumAmount() {
		return (Double) getValue(2);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Service_Tax</code>.
	 */
	public void setServiceTax(Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Service_Tax</code>.
	 */
	public Double getServiceTax() {
		return (Double) getValue(3);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Service_Tax_Amount</code>.
	 */
	public void setServiceTaxAmount(Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Service_Tax_Amount</code>.
	 */
	public Double getServiceTaxAmount() {
		return (Double) getValue(4);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Net_Premium_Amount</code>.
	 */
	public void setNetPremiumAmount(Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Net_Premium_Amount</code>.
	 */
	public Double getNetPremiumAmount() {
		return (Double) getValue(5);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Comission_Rate</code>.
	 */
	public void setComissionRate(Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Comission_Rate</code>.
	 */
	public Double getComissionRate() {
		return (Double) getValue(6);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Comission_Rate_Amount</code>.
	 */
	public void setComissionRateAmount(Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Comission_Rate_Amount</code>.
	 */
	public Double getComissionRateAmount() {
		return (Double) getValue(7);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Collection_Date</code>.
	 */
	public void setCollectionDate(Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Collection_Date</code>.
	 */
	public Date getCollectionDate() {
		return (Date) getValue(8);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Personal_Detail_ID</code>.
	 */
	public void setPersonalDetailId(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Personal_Detail_ID</code>.
	 */
	public Integer getPersonalDetailId() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>slbroking.amount_details.Policy_Number</code>.
	 */
	public void setPolicyNumber(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>slbroking.amount_details.Policy_Number</code>.
	 */
	public String getPolicyNumber() {
		return (String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Double, Double, Double, Double, Double, Double, Double, Date, Integer, String> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Double, Double, Double, Double, Double, Double, Double, Date, Integer, String> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AmountDetails.AMOUNT_DETAILS.AMOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field2() {
		return AmountDetails.AMOUNT_DETAILS.GROSS_PREMIUM_AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field3() {
		return AmountDetails.AMOUNT_DETAILS.TERRORISM_PREMIUM_AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field4() {
		return AmountDetails.AMOUNT_DETAILS.SERVICE_TAX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field5() {
		return AmountDetails.AMOUNT_DETAILS.SERVICE_TAX_AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field6() {
		return AmountDetails.AMOUNT_DETAILS.NET_PREMIUM_AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field7() {
		return AmountDetails.AMOUNT_DETAILS.COMISSION_RATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field8() {
		return AmountDetails.AMOUNT_DETAILS.COMISSION_RATE_AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field9() {
		return AmountDetails.AMOUNT_DETAILS.COLLECTION_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return AmountDetails.AMOUNT_DETAILS.PERSONAL_DETAIL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return AmountDetails.AMOUNT_DETAILS.POLICY_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getAmountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value2() {
		return getGrossPremiumAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value3() {
		return getTerrorismPremiumAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value4() {
		return getServiceTax();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value5() {
		return getServiceTaxAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value6() {
		return getNetPremiumAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value7() {
		return getComissionRate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value8() {
		return getComissionRateAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value9() {
		return getCollectionDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getPersonalDetailId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getPolicyNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value1(Integer value) {
		setAmountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value2(Double value) {
		setGrossPremiumAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value3(Double value) {
		setTerrorismPremiumAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value4(Double value) {
		setServiceTax(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value5(Double value) {
		setServiceTaxAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value6(Double value) {
		setNetPremiumAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value7(Double value) {
		setComissionRate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value8(Double value) {
		setComissionRateAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value9(Date value) {
		setCollectionDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value10(Integer value) {
		setPersonalDetailId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord value11(String value) {
		setPolicyNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AmountDetailsRecord values(Integer value1, Double value2, Double value3, Double value4, Double value5, Double value6, Double value7, Double value8, Date value9, Integer value10, String value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AmountDetailsRecord
	 */
	public AmountDetailsRecord() {
		super(AmountDetails.AMOUNT_DETAILS);
	}

	/**
	 * Create a detached, initialised AmountDetailsRecord
	 */
	public AmountDetailsRecord(Integer amountId, Double grossPremiumAmount, Double terrorismPremiumAmount, Double serviceTax, Double serviceTaxAmount, Double netPremiumAmount, Double comissionRate, Double comissionRateAmount, Date collectionDate, Integer personalDetailId, String policyNumber) {
		super(AmountDetails.AMOUNT_DETAILS);

		setValue(0, amountId);
		setValue(1, grossPremiumAmount);
		setValue(2, terrorismPremiumAmount);
		setValue(3, serviceTax);
		setValue(4, serviceTaxAmount);
		setValue(5, netPremiumAmount);
		setValue(6, comissionRate);
		setValue(7, comissionRateAmount);
		setValue(8, collectionDate);
		setValue(9, personalDetailId);
		setValue(10, policyNumber);
	}
}
