/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.records;


import com.telosws.orm.tables.Onlineusers;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OnlineusersRecord extends UpdatableRecordImpl<OnlineusersRecord> implements Record3<Integer, String, Timestamp> {

	private static final long serialVersionUID = -465800878;

	/**
	 * Setter for <code>slbroking.onlineusers.ID</code>. The PRIMARY AUTO INCREMENT identifier
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>slbroking.onlineusers.ID</code>. The PRIMARY AUTO INCREMENT identifier
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>slbroking.onlineusers.PRIMARY_EMAIL</code>. The primary email address of this registred user
	 */
	public void setPrimaryEmail(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>slbroking.onlineusers.PRIMARY_EMAIL</code>. The primary email address of this registred user
	 */
	public String getPrimaryEmail() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>slbroking.onlineusers.LOGINTIME</code>. The datetime when record was created
	 */
	public void setLogintime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>slbroking.onlineusers.LOGINTIME</code>. The datetime when record was created
	 */
	public Timestamp getLogintime() {
		return (Timestamp) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Timestamp> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Timestamp> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Onlineusers.ONLINEUSERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Onlineusers.ONLINEUSERS.PRIMARY_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Onlineusers.ONLINEUSERS.LOGINTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getPrimaryEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getLogintime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OnlineusersRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OnlineusersRecord value2(String value) {
		setPrimaryEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OnlineusersRecord value3(Timestamp value) {
		setLogintime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OnlineusersRecord values(Integer value1, String value2, Timestamp value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OnlineusersRecord
	 */
	public OnlineusersRecord() {
		super(Onlineusers.ONLINEUSERS);
	}

	/**
	 * Create a detached, initialised OnlineusersRecord
	 */
	public OnlineusersRecord(Integer id, String primaryEmail, Timestamp logintime) {
		super(Onlineusers.ONLINEUSERS);

		setValue(0, id);
		setValue(1, primaryEmail);
		setValue(2, logintime);
	}
}
