/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.records;


import com.telosws.orm.tables.PersonalDetails;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * its holds personal details of insured
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalDetailsRecord extends UpdatableRecordImpl<PersonalDetailsRecord> implements Record11<Integer, String, String, String, String, String, String, String, Date, String, Integer> {

	private static final long serialVersionUID = -946400964;

	/**
	 * Setter for <code>slbroking.personal_details.Personal_ID</code>.
	 */
	public void setPersonalId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Personal_ID</code>.
	 */
	public Integer getPersonalId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Industry</code>.
	 */
	public void setIndustry(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Industry</code>.
	 */
	public String getIndustry() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Name_Of_Individual</code>.
	 */
	public void setNameOfIndividual(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Name_Of_Individual</code>.
	 */
	public String getNameOfIndividual() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Name_of_Company</code>.
	 */
	public void setNameOfCompany(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Name_of_Company</code>.
	 */
	public String getNameOfCompany() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Phone_Number</code>.
	 */
	public void setPhoneNumber(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Phone_Number</code>.
	 */
	public String getPhoneNumber() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Secondary_Number</code>.
	 */
	public void setSecondaryNumber(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Secondary_Number</code>.
	 */
	public String getSecondaryNumber() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Email_Address</code>.
	 */
	public void setEmailAddress(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Email_Address</code>.
	 */
	public String getEmailAddress() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Secondray_Email_Address</code>.
	 */
	public void setSecondrayEmailAddress(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Secondray_Email_Address</code>.
	 */
	public String getSecondrayEmailAddress() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Date_of_Birth</code>.
	 */
	public void setDateOfBirth(Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Date_of_Birth</code>.
	 */
	public Date getDateOfBirth() {
		return (Date) getValue(8);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Gender</code>.
	 */
	public void setGender(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Gender</code>.
	 */
	public String getGender() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>slbroking.personal_details.Address_ID</code>.
	 */
	public void setAddressId(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>slbroking.personal_details.Address_ID</code>.
	 */
	public Integer getAddressId() {
		return (Integer) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, String, String, String, String, String, String, String, Date, String, Integer> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, String, String, String, String, String, String, String, Date, String, Integer> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return PersonalDetails.PERSONAL_DETAILS.PERSONAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PersonalDetails.PERSONAL_DETAILS.INDUSTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PersonalDetails.PERSONAL_DETAILS.NAME_OF_INDIVIDUAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return PersonalDetails.PERSONAL_DETAILS.NAME_OF_COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return PersonalDetails.PERSONAL_DETAILS.PHONE_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return PersonalDetails.PERSONAL_DETAILS.SECONDARY_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return PersonalDetails.PERSONAL_DETAILS.EMAIL_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return PersonalDetails.PERSONAL_DETAILS.SECONDRAY_EMAIL_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field9() {
		return PersonalDetails.PERSONAL_DETAILS.DATE_OF_BIRTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return PersonalDetails.PERSONAL_DETAILS.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return PersonalDetails.PERSONAL_DETAILS.ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPersonalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getIndustry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getNameOfIndividual();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getNameOfCompany();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPhoneNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getSecondaryNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getEmailAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getSecondrayEmailAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value9() {
		return getDateOfBirth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value1(Integer value) {
		setPersonalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value2(String value) {
		setIndustry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value3(String value) {
		setNameOfIndividual(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value4(String value) {
		setNameOfCompany(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value5(String value) {
		setPhoneNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value6(String value) {
		setSecondaryNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value7(String value) {
		setEmailAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value8(String value) {
		setSecondrayEmailAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value9(Date value) {
		setDateOfBirth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value10(String value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord value11(Integer value) {
		setAddressId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalDetailsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Date value9, String value10, Integer value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PersonalDetailsRecord
	 */
	public PersonalDetailsRecord() {
		super(PersonalDetails.PERSONAL_DETAILS);
	}

	/**
	 * Create a detached, initialised PersonalDetailsRecord
	 */
	public PersonalDetailsRecord(Integer personalId, String industry, String nameOfIndividual, String nameOfCompany, String phoneNumber, String secondaryNumber, String emailAddress, String secondrayEmailAddress, Date dateOfBirth, String gender, Integer addressId) {
		super(PersonalDetails.PERSONAL_DETAILS);

		setValue(0, personalId);
		setValue(1, industry);
		setValue(2, nameOfIndividual);
		setValue(3, nameOfCompany);
		setValue(4, phoneNumber);
		setValue(5, secondaryNumber);
		setValue(6, emailAddress);
		setValue(7, secondrayEmailAddress);
		setValue(8, dateOfBirth);
		setValue(9, gender);
		setValue(10, addressId);
	}
}
