/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.records;


import com.telosws.orm.tables.PolicyDetails;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * its policy details of insured
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicyDetailsRecord extends UpdatableRecordImpl<PolicyDetailsRecord> implements Record7<Integer, String, String, String, Integer, Integer, String> {

	private static final long serialVersionUID = 892487160;

	/**
	 * Setter for <code>slbroking.policy_details.Policy_ID</code>.
	 */
	public void setPolicyId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>slbroking.policy_details.Policy_ID</code>.
	 */
	public Integer getPolicyId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>slbroking.policy_details.Insurance_Type</code>.
	 */
	public void setInsuranceType(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>slbroking.policy_details.Insurance_Type</code>.
	 */
	public String getInsuranceType() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>slbroking.policy_details.Product_Name</code>.
	 */
	public void setProductName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>slbroking.policy_details.Product_Name</code>.
	 */
	public String getProductName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>slbroking.policy_details.Policy_Details</code>.
	 */
	public void setPolicyDetails(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>slbroking.policy_details.Policy_Details</code>.
	 */
	public String getPolicyDetails() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>slbroking.policy_details.Person_Details_ID</code>.
	 */
	public void setPersonDetailsId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>slbroking.policy_details.Person_Details_ID</code>.
	 */
	public Integer getPersonDetailsId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>slbroking.policy_details.Policy_Type_Id</code>.
	 */
	public void setPolicyTypeId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>slbroking.policy_details.Policy_Type_Id</code>.
	 */
	public Integer getPolicyTypeId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>slbroking.policy_details.P_Number</code>.
	 */
	public void setPNumber(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>slbroking.policy_details.P_Number</code>.
	 */
	public String getPNumber() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, String, String, Integer, Integer, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, String, String, Integer, Integer, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return PolicyDetails.POLICY_DETAILS.POLICY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PolicyDetails.POLICY_DETAILS.INSURANCE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PolicyDetails.POLICY_DETAILS.PRODUCT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return PolicyDetails.POLICY_DETAILS.POLICY_DETAILS_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return PolicyDetails.POLICY_DETAILS.PERSON_DETAILS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return PolicyDetails.POLICY_DETAILS.POLICY_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return PolicyDetails.POLICY_DETAILS.P_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPolicyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getInsuranceType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getProductName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getPolicyDetails();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getPersonDetailsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getPolicyTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getPNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyDetailsRecord value1(Integer value) {
		setPolicyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyDetailsRecord value2(String value) {
		setInsuranceType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyDetailsRecord value3(String value) {
		setProductName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyDetailsRecord value4(String value) {
		setPolicyDetails(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyDetailsRecord value5(Integer value) {
		setPersonDetailsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyDetailsRecord value6(Integer value) {
		setPolicyTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyDetailsRecord value7(String value) {
		setPNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyDetailsRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Integer value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PolicyDetailsRecord
	 */
	public PolicyDetailsRecord() {
		super(PolicyDetails.POLICY_DETAILS);
	}

	/**
	 * Create a detached, initialised PolicyDetailsRecord
	 */
	public PolicyDetailsRecord(Integer policyId, String insuranceType, String productName, String policyDetails, Integer personDetailsId, Integer policyTypeId, String pNumber) {
		super(PolicyDetails.POLICY_DETAILS);

		setValue(0, policyId);
		setValue(1, insuranceType);
		setValue(2, productName);
		setValue(3, policyDetails);
		setValue(4, personDetailsId);
		setValue(5, policyTypeId);
		setValue(6, pNumber);
	}
}
