/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.records;


import com.telosws.orm.tables.PolicyType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicyTypeRecord extends UpdatableRecordImpl<PolicyTypeRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = -1299060902;

	/**
	 * Setter for <code>slbroking.policy_type.policy_type_id</code>.
	 */
	public void setPolicyTypeId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>slbroking.policy_type.policy_type_id</code>.
	 */
	public Integer getPolicyTypeId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>slbroking.policy_type.policy_type_name</code>.
	 */
	public void setPolicyTypeName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>slbroking.policy_type.policy_type_name</code>.
	 */
	public String getPolicyTypeName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return PolicyType.POLICY_TYPE.POLICY_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PolicyType.POLICY_TYPE.POLICY_TYPE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPolicyTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getPolicyTypeName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyTypeRecord value1(Integer value) {
		setPolicyTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyTypeRecord value2(String value) {
		setPolicyTypeName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PolicyTypeRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PolicyTypeRecord
	 */
	public PolicyTypeRecord() {
		super(PolicyType.POLICY_TYPE);
	}

	/**
	 * Create a detached, initialised PolicyTypeRecord
	 */
	public PolicyTypeRecord(Integer policyTypeId, String policyTypeName) {
		super(PolicyType.POLICY_TYPE);

		setValue(0, policyTypeId);
		setValue(1, policyTypeName);
	}
}
