/**
 * This class is generated by jOOQ
 */
package com.telosws.orm.tables.records;


import com.telosws.orm.tables.User;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record13<Integer, String, String, String, String, String, String, String, String, Timestamp, Timestamp, String, Integer> {

	private static final long serialVersionUID = -764012201;

	/**
	 * Setter for <code>slbroking.user.ID</code>. The PRIMARY AUTO INCREMENT identifier
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>slbroking.user.ID</code>. The PRIMARY AUTO INCREMENT identifier
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>slbroking.user.FIRST_NAME</code>. The FirstName/GivenName of the registred user
	 */
	public void setFirstName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>slbroking.user.FIRST_NAME</code>. The FirstName/GivenName of the registred user
	 */
	public String getFirstName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>slbroking.user.MIDDLE_NAME</code>. The MiddleName/Initials of the registred user
	 */
	public void setMiddleName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>slbroking.user.MIDDLE_NAME</code>. The MiddleName/Initials of the registred user
	 */
	public String getMiddleName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>slbroking.user.LAST_NAME</code>. The LastName/SurName of the registred user
	 */
	public void setLastName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>slbroking.user.LAST_NAME</code>. The LastName/SurName of the registred user
	 */
	public String getLastName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>slbroking.user.PASSWORD</code>. The encrypted password of the registred user
	 */
	public void setPassword(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>slbroking.user.PASSWORD</code>. The encrypted password of the registred user
	 */
	public String getPassword() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>slbroking.user.ROLE</code>. The role of registred user - EMP or HR
	 */
	public void setRole(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>slbroking.user.ROLE</code>. The role of registred user - EMP or HR
	 */
	public String getRole() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>slbroking.user.PRIMARY_EMAIL</code>. The primary email address of this registred user
	 */
	public void setPrimaryEmail(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>slbroking.user.PRIMARY_EMAIL</code>. The primary email address of this registred user
	 */
	public String getPrimaryEmail() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>slbroking.user.PRIMARY_PHONE</code>. The primary phone number of this registred user
	 */
	public void setPrimaryPhone(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>slbroking.user.PRIMARY_PHONE</code>. The primary phone number of this registred user
	 */
	public String getPrimaryPhone() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>slbroking.user.STATUS</code>. The status of this registred user
	 */
	public void setStatus(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>slbroking.user.STATUS</code>. The status of this registred user
	 */
	public String getStatus() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>slbroking.user.CREATED_ON</code>. The datetime when record was created
	 */
	public void setCreatedOn(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>slbroking.user.CREATED_ON</code>. The datetime when record was created
	 */
	public Timestamp getCreatedOn() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>slbroking.user.UPDATED_ON</code>. The datetime when record was updated
	 */
	public void setUpdatedOn(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>slbroking.user.UPDATED_ON</code>. The datetime when record was updated
	 */
	public Timestamp getUpdatedOn() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>slbroking.user.COMMENTS</code>.
	 */
	public void setComments(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>slbroking.user.COMMENTS</code>.
	 */
	public String getComments() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>slbroking.user.company_id</code>.
	 */
	public void setCompanyId(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>slbroking.user.company_id</code>.
	 */
	public Integer getCompanyId() {
		return (Integer) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Integer, String, String, String, String, String, String, String, String, Timestamp, Timestamp, String, Integer> fieldsRow() {
		return (Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Integer, String, String, String, String, String, String, String, String, Timestamp, Timestamp, String, Integer> valuesRow() {
		return (Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return User.USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return User.USER.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return User.USER.MIDDLE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return User.USER.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return User.USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return User.USER.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return User.USER.PRIMARY_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return User.USER.PRIMARY_PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return User.USER.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return User.USER.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return User.USER.UPDATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return User.USER.COMMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return User.USER.COMPANY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getMiddleName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getPrimaryEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getPrimaryPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getUpdatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getComments();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getCompanyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value3(String value) {
		setMiddleName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value4(String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value5(String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value6(String value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value7(String value) {
		setPrimaryEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value8(String value) {
		setPrimaryPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value9(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value10(Timestamp value) {
		setCreatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value11(Timestamp value) {
		setUpdatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value12(String value) {
		setComments(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value13(Integer value) {
		setCompanyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Timestamp value10, Timestamp value11, String value12, Integer value13) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(Integer id, String firstName, String middleName, String lastName, String password, String role, String primaryEmail, String primaryPhone, String status, Timestamp createdOn, Timestamp updatedOn, String comments, Integer companyId) {
		super(User.USER);

		setValue(0, id);
		setValue(1, firstName);
		setValue(2, middleName);
		setValue(3, lastName);
		setValue(4, password);
		setValue(5, role);
		setValue(6, primaryEmail);
		setValue(7, primaryPhone);
		setValue(8, status);
		setValue(9, createdOn);
		setValue(10, updatedOn);
		setValue(11, comments);
		setValue(12, companyId);
	}
}
